# SPDX-License-Identifier: GPL-2.0-or-later
# Realtek DHC pin control drivers
obj-$(CONFIG_PINCTRL_RTD)		+= pinctrl-rtd.o
obj-$(CONFIG_PINCTRL_RTD1619B)		+= pinctrl-rtd1619b.o
obj-$(CONFIG_PINCTRL_RTD1319D)		+= pinctrl-rtd1319d.o
obj-$(CONFIG_PINCTRL_RTD1315E)		+= pinctrl-rtd1315e.o
obj-$(CONFIG_PINCTRL_RTD119X)	+= pinctrl-rtd119x.o
obj-$(CONFIG_PINCTRL_RTD129x)	+= pinctrl-rtd129x.o
obj-$(CONFIG_PINCTRL_RTD139x)	+= pinctrl-rtd139x.o
obj-$(CONFIG_PINCTRL_RTD16xx)	+= pinctrl-rtd16xx.o
obj-$(CONFIG_PINCTRL_RTD13xx)	+= pinctrl-rtd13xx.o
