[Index]
pd_bitmap = 0x6
pd_sysid_sg0 = 1
pd_sysid_sda = 1
pd_sysid_sg1 = 2
pd_sysid_sdb = 2

[PhysicalDisk_1]
port_id = 1
att_phy_id = -1
pd_sys_id = sg0
enc_sys_id = root
pd_sys_name = /dev/sda
pd_ctrl_name = /dev/sg0
pd_bus_name = 2:0:0:0
wwn = 50014EE2B992FDC0
real_wwn = 50014EE2B992FDC0
type = 0
form = 0
vendor = WDC
model = WD10EFRX-68FYTN0
serial_no = WD-WCC4J1ZHDJHN
status = 0
capabilities = 207191
sector_size = 512
capacity = 1953525168
revision = 82.00A82
protocol_ver = 589824
link_speed = 8
max_link_speed = 8
pd_max_link_speed = 0
read_speed = none
read_iops = none
write_speed = none
write_iops = none
rotation_speed = 5400

[PhysicalDisk_2]
port_id = 2
att_phy_id = -1
pd_sys_id = sg1
enc_sys_id = root
pd_sys_name = /dev/sdb
pd_ctrl_name = /dev/sg1
pd_bus_name = 3:0:0:0
wwn = 50014EE2643D5BA2
real_wwn = 50014EE2643D5BA2
type = 0
form = 0
vendor = WDC
model = WD10EFRX-68FYTN0
serial_no = WD-WCC4J2LN92D2
status = 0
capabilities = 207191
sector_size = 512
capacity = 1953525168
revision = 82.00A82
protocol_ver = 589824
link_speed = 8
max_link_speed = 8
pd_max_link_speed = 0
read_speed = none
read_iops = none
write_speed = none
write_iops = none
rotation_speed = 5400
