[Index]
enc_bitmap = 0x700000001
enc_sysid_root = 0
pd_wwn_50014EE2B992FDC0 = 00000001
pd_wwn_50014EE2643D5BA2 = 00000002
enc_sysid_root_boot = 32
enc_sysid_root_usb = 33
pd_wwn_01016442b6ec8dad7fb7c8222a88893d = 00210001
enc_sysid_root_mmc = 34

[Enclosure_0]
enc_id = 0
enc_sys_id = root
serial = Q174B07559
vendor = QNAP
model = TS-228
status = 0
protocol = 0
capability = 0x824a0384
extended_capability = 0x0
max_disk_num = 2
max_fan_num = 1
max_cpu_fan_num = 0
default_cpu_fan_count = 0
factory_cpu_fan_count = 0
max_temp_num = 1
max_pcie_num = 0
max_nic_num = 1
max_conn_num = 0
max_ujbod_num = -1
max_cpu_num = 1
enc_parent_sys_id = root
enc_parent_port_id = 0
stack_id = 0
revision = 
cache_port_bitmap = 0x0
ss_max_channels = 8
ss_free_channels = 2
child_bitmap = 0x700000000

[Enclosure_32]
enc_id = 32
enc_sys_id = root_boot
vendor = QNAP
model = BOOT
status = 0
protocol = -1
capability = 0x0
extended_capability = 0x0
max_disk_num = 1
max_fan_num = 0
max_cpu_fan_num = 0
default_cpu_fan_count = 0
factory_cpu_fan_count = 0
max_temp_num = 0
max_pcie_num = 0
max_nic_num = 0
max_conn_num = 0
max_ujbod_num = 0
max_cpu_num = 0
enc_parent_sys_id = root
enc_parent_port_id = 0
stack_id = 1
revision = 
cache_port_bitmap = 0x0

[BootDisk_0]
port_id = 0
att_phy_id = -1
pd_sys_id = emmc_1
enc_sys_id = root_boot
pd_sys_name = /dev/mmcblk0p
pd_ctrl_name = 
pd_bus_name = 
type = 0
form = 0
vendor = 
model = 
serial_no = 
status = 0
capabilities = 32
sector_size = 512
capacity = 4096
revision = 
protocol_ver = 0
link_speed = 0
max_link_speed = 0
pd_max_link_speed = 0
read_speed = none
read_iops = none
write_speed = none
write_iops = none
rotation_speed = 0

[Enclosure_33]
enc_id = 33
enc_sys_id = root_usb
vendor = QNAP
model = USB
status = 0
protocol = 2
capability = 0x0
extended_capability = 0x0
max_disk_num = 2
max_fan_num = 0
max_cpu_fan_num = 0
default_cpu_fan_count = 0
factory_cpu_fan_count = 0
max_temp_num = 0
max_pcie_num = 0
max_nic_num = 0
max_conn_num = 0
max_ujbod_num = 0
max_cpu_num = 0
enc_parent_sys_id = root
enc_parent_port_id = 0
stack_id = 1
revision = 
cache_port_bitmap = 0x0

[Enclosure_34]
enc_id = 34
enc_sys_id = root_mmc
vendor = QNAP
model = Memory Card
status = 0
protocol = 7
capability = 0x0
extended_capability = 0x0
max_disk_num = 1
max_fan_num = 0
max_cpu_fan_num = 0
default_cpu_fan_count = 0
factory_cpu_fan_count = 0
max_temp_num = 0
max_pcie_num = 0
max_nic_num = 0
max_conn_num = 0
max_ujbod_num = 0
max_cpu_num = 0
enc_parent_sys_id = root
enc_parent_port_id = 0
stack_id = 1
revision = 
cache_port_bitmap = 0x0

[Global]
Service Mode = 0
