obj-$(CONFIG_ARCH_REALTEK)		+= rtd119x_restart.o
obj-$(CONFIG_HOTPLUG_CPU)		+= rtd119x_hotplug.o
obj-$(CONFIG_ARCH_REALTEK)		+= rtk_chip.o
obj-$(CONFIG_ARCH_REALTEK)		+= rtk_usb.o
obj-$(CONFIG_SCPU_SRAMCTL_RTD119X)      += rtd119x_scpu_sramctl.o
