# Leave free space so U-Boot can set bootargs / stdout-path.
DTC_FLAGS += -p 1024

dtb-$(CONFIG_ARCH_RTD119X) += \
        rtd-119x-horseradish.dtb \
        rtd-119x-horseradish-tee.dtb \
        rtd-119x-qa-rescue.dtb \
	rtd-119x-horseradish-nand.dtb \
	rtd-119x-qa-rescue-nand.dtb \
        rtd-119x-horseradish-QNAP-TS-X28.dtb
