obj-y += rtk_memory_remap.o rtk_barrier.o rtk_sb2_dbg.o rtk_dc_sys_dbg.o
obj-y += rtk_chip.o
obj-y += dummy_uctrl.o
obj-y += rtk_sb2_sem.o
obj-$(CONFIG_RTK_RPC) += rpc/
obj-$(CONFIG_RTK_MMIO) += rtk_mmio.o
obj-y += info/
obj-$(CONFIG_RTK_PERFCNT) += perfcnt/
