# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_REALTEK) += \
	rtd1195-horseradish.dtb \
	rtd1195-mele-x1000.dtb

# Leave free space so U-Boot can set bootargs / stdout-path.
DTC_FLAGS += -p 1024

dtb-$(CONFIG_ARCH_RTD119X) += \
	rtd1195-qnap-ts-228.dtb
